### ISSUE TITLE
GitHub Actions and tox

### ISSUE THREAD

**Issue by Mischback** [Mischback/django-calingen#37]
- ``tox`` is run in combination with ``tox-gh-actions``
- ``ci-default.yml`` workflow does limit the testing matrix (regarding windows' Python versions)

The mentioned limitation can be implemented directly in ``tox.ini`` / ``pyproject.toml``, using something like 

```
[tox]
envlist = 
  py37-django{31,32}-{linux,macos}
  py38-django{31,32,40}-{linux,macos}
  py{39,310}-django{31,32,40}-{linux,macos,windows}

[gh-actions]
python =
  3.7: py37
  3.8: py38
  3.9: py39
  3.10: py310

[gh-actions:env]
PLATFORM =
  ubuntu-latest: linux
  macos-latest: macos
  windows-latest: windows
```

The above would make parts of ``ci-default.yml`` obsolete:

```
  testing:
    name: Run tests on ${{ matrix.os }} for ${{ matrix.python-version }}
    needs: linting
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.7", "3.8", "3.9", "3.10"]
        exclude:
          # exclude Python 3.7 and 3.8 on Windows
          # The excluded Python versions are provided without JSON1 extension of
          # sqlite
          - os: windows-latest
            python-version: "3.7"
          - os: windows-latest
            python-version: "3.8"
    runs-on: ${{ matrix.os }}
```
(The whole ``exclude`` block could be removed!)

**Pro**
- all logical constraints regarding testing are provided in ``tox``'s configuration and not in the CI-specific configuration.

**Con**
- slightly increased complexity of ``tox.ini`` / ``pyproject.toml``
